theme = "lighter_purple"

[editor]
auto-completion = false
completion-replace = true
cursorline = true

[editor.auto-save]
focus-lost = true
# This line will auto-save after 3 seconds of inactivity.
# after-delay.enable = true

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.lsp]
auto-signature-help = false

# [editor.inline-diagnostics]
# cursor-line = "error"

[keys.normal]
C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"
S-down = '@x"ld"lp;' # Macro: Shift line down, using register "l".
S-up = '@x"ld<up>"lP;' # Macro: Shift line up, using register "l".
W = "@miw" # Macro: Select entire word.
C-x = "completion"
# Scroll viewport one line without moving cursor.
j = "scroll_up" 
k = "scroll_down"
A-k = "hover"

[keys.insert]
C-left = "jump_view_left"
C-right = "jump_view_right"
C-up = "jump_view_up"
C-down = "jump_view_down"
A-h = "signature_help"
A-k = "hover"
C-x = "completion"
