[[language]]
name = "python"
language-servers = ["pylsp", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language.formatter]
command = "ruff"
args = ["format", "-"]
