[[language]]
name = "python"
language-servers = ["pylsp", "ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[language.formatter]
command = "ruff"
args = ["format", "-"]

[language-server.pylsp.config.pylsp.plugins]
pycodestyle.enabled = false
pyflakes.enabled = false
autopep8.enabled = false
mccabe.enabled = false
