inherits = "base16_default"

keyword = { fg = "light-magenta"}
namespace = { fg = "cyan"}
function = { fg = "light-blue" }

"ui.cursorline.primary" = { bg = "#303030" }
# "ui.selection" = { fg = "black", bg = "light-blue" }
# "ui.selection.primary" = { fg = "white", bg = "light-blue" }
